# Required
version: 2

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

conda:
    environment: environment_doc.yml

python:
  version: 3.8
  install:
    - method: pip
      path: .

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
